---@meta
--
-- Type definitions for the `bonsaiwm` Lua config table.
--

---@class bonsaiwm.Rule
---Application identifier: app_id (Wayland xdg-toplevel) or class (X11/XWayland).
---Matched as a **substring** against the client's app_id/class.
---Nil or omitted = match any application.
---@field id? string
---Window title. Matched as a **substring** against the client's title.
---Nil or omitted = match any title.
---@field title? string
---Tag bitmask selecting which tags the client starts on.
---Bit `n` (0-indexed) corresponds to tag `n+1`. `0` = keep currently visible
---tags. Example: `1 << 8` starts the client on tag "9" only.
---@field tags integer
---Whether the client should float instead of being tiled.
---`1` = floating, `0` = tiled. Default `0` when omitted.
---@field isfloating integer
---Monitor to place the client on, as a 0-based index into the monitor list.
---`-1` = the currently selected monitor. Default `-1` when omitted.
---@field monitor integer

---@class bonsaiwm.Keymap
---Modifiers, case-insensitive, joined with `+`: `"Alt"`, `"Alt+Shift"`,
---`"Ctrl+Alt"`, `"Super"`. `"none"` = no modifier required.
---@field mod string
---XKB keysym name (case-insensitive on xkbcommon ≥ 0.5.0): `"Return"`,
---`"p"`, `"1"`, `"XF86MonBrightnessUp"`, etc.
---**Note:** Shift changes the keysym sent by the keyboard (e.g. `"1"` →
---`"exclam"` when Shift is held), so a binding for `Alt+Shift+1` needs its
---own entry with `key = "exclam"`.
---@field key string
---Which compositor action to invoke, one of `bonsaiwm.action.*`:
---`spawn`, `focusstack`, `incnmaster`, `setmfact`, `zoom`, `view`,
---`toggleview`, `tag`, `toggletag`, `setlayout`, `togglefloating`,
---`togglefullscreen`, `focusmon`, `tagmon`, `killclient`, `quit`,
---`load_config`, `togglegaps`, `defaultgaps`, `incgaps`, `chvt`, `none`.
---Use `none` to shadow a default binding with a noop (effectively disabling it).
---@field action integer
---Argument passed to the action. Type depends on the action:
---  - `spawn`           → string (command line, e.g. `"foot"`)
---  - `view`/`toggleview`/`tag`/`toggletag` → tag NUMBER 1-9
---    (internally converted to the `1<<(n-1)` bitmask the action expects)
---  - `focusstack`/`incnmaster`/`focusmon`/`tagmon`/`incgaps`/`chvt` → integer
---  - `setmfact`/`setlayout` → number (float or integer)
---  - most others       → omit / nil
---@field arg? integer|number|string

---@class bonsaiwm
---Enables tiling gaps when nonzero.
---@field enablegaps integer
---When nonzero, outer gaps are hidden if a window is the only one on the tag.
---@field smartgaps integer
---Outer horizontal gap (pixels) between clients and the screen edge.
---@field gappoh integer
---Outer vertical gap (pixels) between clients and the screen edge.
---@field gappov integer
---Inner horizontal gap (pixels) between adjacent clients.
---@field gappih integer
---Inner vertical gap (pixels) between adjacent clients.
---@field gappiv integer
---When nonzero, focus follows the pointer (focus the window under the cursor).
---@field sloppyfocus integer
---Border thickness around clients (pixels).
---@field borderpx integer
---Keyboard repeat rate (keys per second).
---@field repeat_rate integer
---Keyboard repeat delay (ms) before a held key starts repeating.
---@field repeat_delay integer
---Root (background) color as a hex string, e.g. "#1a1b26" or "#1a1b26ff".
---@field rootcolor string
---Unfocused-client border color. Hex string.
---@field bordercolor string
---Focused-client border color. Hex string.
---@field focuscolor string
---Urgent-client border color. Hex string.
---@field urgentcolor string
---Backdrop color shown behind a fullscreen client. Hex string.
---@field fullscreen_bg string
---Window rules. Rebuilt from this table on every config reload (Mod-Shift-R).
---May be empty or omitted; in that case no rules apply and clients keep their
---default tags/monitor. At least one example is usually present.
---@field rules bonsaiwm.Rule[]
---Key bindings. This is where *all* user-facing bindings live; the C
---defaults (`keys_defaults[]` in `config.c`) are deliberately minimal —
---just escape hatches (Mod-Shift-R reload, Ctrl-Alt-Fn VT switch) that are
---always present so you can recover from a broken config. Everything else
---(spawn, focus, tags, layouts, kill, quit, gaps, etc.) must be defined here.
---If an entry has the same (mod, key) as a C default, the lua entry wins.
---Use `action = bonsaiwm.action.none` as an explicit noop placeholder.
---@field keymaps bonsaiwm.Keymap[]

bonsaiwm = {}
